preload = /home/spample/.dots/.config/hypr-stuff/wallpapers/unlucky-1.jpg
wallpaper = eDP-1,/home/spample/.dots/.config/hypr-stuff/wallpapers/unlucky-1.jpg
wallpaper = HDMI-A-1,/home/spample/.dots/.config/hypr-stuff/wallpapers/unlucky-1.jpg
