-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
    },
})

--listener {

--  timeout = 600

--  on-timeout = loginctl lock-session

--}

-- crashing with caelestial shell

--listener {

--  timeout = 1200

--  on-timeout = hyprctl dispatch dpms off

--  on-resume = hyprctl dispatch dpms on

--}

--listener {

--  timeout = 1500

--  on-timeout = systemctl suspend

--}
