preload = /home/spample/.dots/.config/hypr-stuff/wallpapers/cool-bg-6.jpg
wallpaper = eDP-1,/home/spample/.dots/.config/hypr-stuff/wallpapers/cool-bg-6.jpg
wallpaper = HDMI-A-1,/home/spample/.dots/.config/hypr-stuff/wallpapers/cool-bg-6.jpg
