-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    wallpaper = {
        path = "~/.dots/.config/hypr-stuff/wallpapers/cool-bg-1.png",
        fit_mode = "fill",
        splash = false,
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output
