# Execute your favorite apps at launch
exec-once = qs &
#exec-once = dunst
exec = swaync
exec = fcitx5
#exec-once = hyprpaper
exec-once = /usr/bin/kdeconnect-indicator
exec-once = /lib/kdeconnectd
exec-once = hypridle
exec-once = nm-applet --indicator

exec-once = /home/spample/.dots/.config/hypr-stuff/scripts/hyprpaper-auto.sh


# Clipboard history
exec-once = clipse -listen # run listener on startup
