# Execute your favorite apps at launch
exec = qs &
#exec-once = dunst
exec = swaync
exec = fcitx5
#exec-once = hyprpaper
exec-once = /usr/bin/kdeconnect-indicator
exec-once = /lib/kdeconnectd
exec-once = hypridle
exec-once = nm-applet --indicator

exec-once = ~/.dots/.config/hypr-stuff/scripts/random_wallpaper.sh

# Clipboard history
exec-once = clipse -listen
#exec-once = wl-clip-persist --clipboard regular
