# Execute your favorite apps at launch
#exec-once = qs &
exec-once = waybar &
#exec-once = dunst
exec = swaync
exec = fcitx5
#exec-once = hyprpaper
exec-once = /usr/bin/kdeconnect-indicator
exec-once = /lib/kdeconnectd
exec-once = hypridle
exec-once = nm-applet --indicator

exec-once = wpaperd -d
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 1 silent] kitty

# Clipboard history
exec-once = clipse -listen # run listener on startup
