# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant = 
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    accel_profile = flat

    touchpad {
      natural_scroll = true
      disable_while_typing = false
      tap-to-click = true

    }
  sensitivity = 1 # -1.0 - 1.0, 0 means no modification.

}

device {
  name = razer-razer-basilisk-v3-pro-mouse
  sensitivity = -1.0
}
