# See https://wiki.hyprland.org/Configuring/Monitors/


#
# Laptop Display Configuring
#

# Laptop display
#monitor=eDP-1,2560x1600@165,0x0,1.3333



#
# Computer Display Configuring
#

# Computer Display Left
monitor=DP-3,1920x1080@144,0x0,1
# Computer Display Right
monitor=DP-2,1920x1080@144,1920x0,1


# Display for HDMI
#monitor=eDP-1,1920x1080@60,0x0,1.3333





#
# HDMI Display Configuring
#

# Mirror HDMI from eDP-1
#monitor=HDMI-A-1,1920x1080@60,1920x0,1,mirror,eDP-1

# Extend HDMI from eDP-1
# monitor=HDMI-A-1,1920x1080@60,1920x0,1.3333
