# See https://wiki.hyprland.org/Configuring/Monitors/

# Laptop display
monitor=eDP-1,2560x1600@165,0x0,1.3333

# Mirror HDMI to eDP-1
#monitor=HDMI-A-1,1920x1080@60,auto,1.3333,mirror,eDP-1

# Mirror HDMI to eDP-1
monitor=HDMI-A-1,1920x1080@60,1920x0,1.3333
