# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

#
# App Window-Rules
#
windowrule {
  name = flameshot-windowRule
  match:class = ^(flameshot)
  float = on
  move = 0 0
  pin = on
  fullscreen_state = 0 3
}


windowrule {
  name = clipse-float
  match:class = ^(clipse)$
  float = true
  size = 622 652
  pin = true
  center = true
}


#
# --- Opacity ----
#
windowrule {
  name = zen-opacity
  match:class = ^(zen)$
  opacity = 0.92
}
windowrule {
  name = firefox-opacity
  match:class = ^(firefox)$
  opacity = 0.95
}

windowrule {
  name = nemo-opacity
  match:class = ^(nemo)$
  opacity = 0.85 0.75
}

windowrule {
  name = discord-opacity
  match:class = ^(discord)$
  opacity = 0.85 0.75
}

windowrule {
  name = vesktop-opacity
  match:class = ^(vesktop)$
  opacity = 0.85 0.75
}
