[ids]
*

[main]
xf86touchpadtoggle = xf86touchpadtoggle
# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
# Set this to be on root dir = /etc/keyd/default.conf

